openapi: "3.0.1"
info:
  title: "binoclahomework"
  version: "1.0"
servers:
  - url: "https://1zl9ql93ye.execute-api.us-east-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: ""
tags:
  - name: "httpapi:createdBy"
    x-amazon-apigateway-tag-value: "SAM"
#  Some tags are hidden due to security
paths:
  #  Some paths & headers are hidden due to security
  /$default:
    x-amazon-apigateway-any-method:
      isDefaultRoute: true
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:563064180346:function:binoclahomework-DemoNative-KeKnImDEpSqy/invocations"
        connectionType: "INTERNET"
x-amazon-apigateway-importexport-version: "1.0"
